spring:
  data:
    mongodb:
      database: library_app
      port: 5050

  output:
    ansi:
      enabled: always

mongock:
  change-logs-scan-package:
    - ru.revseev.library.repo.changelog.mongo
  runner-type: "InitializingBean"
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

hystrix:
  command:
    generateReport:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
      requestLog:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    leaseExpirationDurationInSeconds: 90
    leaseRenewalIntervalInSeconds: 30
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 15000

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,logfile
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  health:
    defaults:
      enabled: true
logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    ru: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'